//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicManagement.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicManagement.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album textbox cleared.
        /// </summary>
        public static string AlbumTextBoxCleared {
            get {
                return ResourceManager.GetString("AlbumTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected songs album updated.
        /// </summary>
        public static string AlbumUpdated {
            get {
                return ResourceManager.GetString("AlbumUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All songs albums updated.
        /// </summary>
        public static string AllSongsAlbumUpdated {
            get {
                return ResourceManager.GetString("AllSongsAlbumUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All songs author updated.
        /// </summary>
        public static string AllSongsAuthorUpdated {
            get {
                return ResourceManager.GetString("AllSongsAuthorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all.
        /// </summary>
        public static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author textbox cleared.
        /// </summary>
        public static string AuthorTextBoxCleared {
            get {
                return ResourceManager.GetString("AuthorTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected songs author updated.
        /// </summary>
        public static string AuthorUpdated {
            get {
                return ResourceManager.GetString("AuthorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with loaded songs. Please be sure that you selected folder.
        /// </summary>
        public static string CannotLoadSongs {
            get {
                return ResourceManager.GetString("CannotLoadSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name cannot be empty.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name textbox cleared.
        /// </summary>
        public static string FileNameTextBoxCleared {
            get {
                return ResourceManager.GetString("FileNameTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form cleared.
        /// </summary>
        public static string FormTextBoxCleared {
            get {
                return ResourceManager.GetString("FormTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directory selected.
        /// </summary>
        public static string NoDictionarySelected {
            get {
                return ResourceManager.GetString("NoDictionarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non song on list.
        /// </summary>
        public static string NoSongs {
            get {
                return ResourceManager.GetString("NoSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non song was selected.
        /// </summary>
        public static string NoSongsSelected {
            get {
                return ResourceManager.GetString("NoSongsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs list cleared.
        /// </summary>
        public static string SongsListCleared {
            get {
                return ResourceManager.GetString("SongsListCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs loaded.
        /// </summary>
        public static string SongsLoaded {
            get {
                return ResourceManager.GetString("SongsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs unselected.
        /// </summary>
        public static string SongsUnselected {
            get {
                return ResourceManager.GetString("SongsUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song title textbox cleared.
        /// </summary>
        public static string TitleTextBoxCleared {
            get {
                return ResourceManager.GetString("TitleTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected songs title updated.
        /// </summary>
        public static string TitleUpdated {
            get {
                return ResourceManager.GetString("TitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        public static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
    }
}
