//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicManagement.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicManagement.Language.Resources.PL", typeof(PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyszczono pole tekstowe album.
        /// </summary>
        public static string AlbumTextBoxCleared {
            get {
                return ResourceManager.GetString("AlbumTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album wybranych piosenek zaktualizowany.
        /// </summary>
        public static string AlbumUpdated {
            get {
                return ResourceManager.GetString("AlbumUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album wszystkich piosenek na liście zakutalizowany.
        /// </summary>
        public static string AllSongsAlbumUpdated {
            get {
                return ResourceManager.GetString("AllSongsAlbumUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor wszystkich piosenek na liście zakutalizowany.
        /// </summary>
        public static string AllSongsAuthorUpdated {
            get {
                return ResourceManager.GetString("AllSongsAuthorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyszczono pole tekstowe autor.
        /// </summary>
        public static string AuthorTextBoxCleared {
            get {
                return ResourceManager.GetString("AuthorTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor wybranych piosenek zaktualizowany.
        /// </summary>
        public static string AuthorUpdated {
            get {
                return ResourceManager.GetString("AuthorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem z załadowaniem piosenek. Proszę sprawdź czy wybrano właściwy folder.
        /// </summary>
        public static string CannotLoadSongs {
            get {
                return ResourceManager.GetString("CannotLoadSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa nazwa nie może być pusta.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyszczono pole tekstowe nazwa pliku.
        /// </summary>
        public static string FileNameTextBoxCleared {
            get {
                return ResourceManager.GetString("FileNameTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie pola wyczyszczono.
        /// </summary>
        public static string FormTextBoxCleared {
            get {
                return ResourceManager.GetString("FormTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano folderu.
        /// </summary>
        public static string NoDictionarySelected {
            get {
                return ResourceManager.GetString("NoDictionarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak piosenek na liście.
        /// </summary>
        public static string NoSongs {
            get {
                return ResourceManager.GetString("NoSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zaznaczonych piosenek.
        /// </summary>
        public static string NoSongsSelected {
            get {
                return ResourceManager.GetString("NoSongsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyszczono listę piosenek.
        /// </summary>
        public static string SongsListCleared {
            get {
                return ResourceManager.GetString("SongsListCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piosenki załadowane.
        /// </summary>
        public static string SongsLoaded {
            get {
                return ResourceManager.GetString("SongsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piosenki odzanczone.
        /// </summary>
        public static string SongsUnselected {
            get {
                return ResourceManager.GetString("SongsUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyszczono pole tekstowe tytuł.
        /// </summary>
        public static string TitleTextBoxCleared {
            get {
                return ResourceManager.GetString("TitleTextBoxCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł wybranych piosenek zaktualizowany.
        /// </summary>
        public static string TitleUpdated {
            get {
                return ResourceManager.GetString("TitleUpdated", resourceCulture);
            }
        }
    }
}
